FROM node AS prod
WORKDIR /app
COPY package*.json ./
RUN npm install --save --legacy-peer-deps
COPY . .

COPY ./public/ /public 


RUN npm run build

FROM nginx:alpine AS Web
WORKDIR /usr/share/nginx/html
COPY --from=prod /app/build .
EXPOSE 80
# run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]