FROM tiangolo/node-frontend as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm i
COPY ./ /app/
RUN npm run build
FROM nginx
COPY --from=build-stage /app/build/ /usr/share/nginx/html 
COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf